apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- controller-certificate.yaml
- controller-crb.yaml
- controller-deploy.yaml
- controller-sa.yaml
- controller-svc.yaml
commonLabels:
  app.kubernetes.io/component: controller
images:
- name: k8s-policies-controller:latest
  newName: k8s-policies-controller
  newTag: bbd86f1-2-gccdf9e8
