apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gcpauth
  annotations:
    cert-manager.io/inject-ca-from: policies/gcpauth-controller
webhooks:
- name: gcpauth-controller.policies.svc.cluster.local
  clientConfig:
    service:
      name: gcpauth-controller
      namespace: default
      port: 443
      path: /mutate-v1-serviceaccounts
    caBundle: ""
  failurePolicy: Ignore
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - k8s-policies-controller
  reinvocationPolicy: Never
  rules:
  - resources:
    - serviceaccounts
    apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
  sideEffects: NoneOnDryRun
  timeoutSeconds: 5
